### ISSUE TITLE
In ring.session error when response is not a map

### ISSUE THREAD

**Issue by arichiardi** [ring-clojure/ring#250]
Specifically, in one case I get an exception when using `aleph`:

```
21:34:08.219 [manifold-pool-2-7] ERROR aleph.http.server - error in HTTP handler
java.lang.IllegalArgumentException: contains? not supported on type: manifold.deferred.Deferred
    at clojure.lang.RT.contains(RT.java:814)
    at clojure.core$contains_QMARK_.invokeStatic(core.clj:1443)
    at clojure.core$contains_QMARK_.invoke(core.clj:1435)
    at ring.middleware.session$bare_session_response.invokeStatic(session.clj:44)
    at ring.middleware.session$bare_session_response.doInvoke(session.clj:42)
    at clojure.lang.RestFn.invoke(RestFn.java:442)
    at ring.middleware.session$session_response.invokeStatic(session.clj:71)
    at ring.middleware.session$session_response.doInvoke(session.clj:64)
    at clojure.lang.RestFn.invoke(RestFn.java:442)
    at ring.middleware.session$wrap_session$fn__42328.invoke(session.clj:103)
    at aleph.http.server$handle_request$fn__37126$f__24528__auto____37127.invoke(server.clj:155)
    at clojure.lang.AFn.run(AFn.java:22)
    at io.aleph.dirigiste.Executor$Worker$1.run(Executor.java:62)
    at manifold.executor$thread_factory$reify__24410$f__24411.invoke(executor.clj:36)
    at clojure.lang.AFn.run(AFn.java:22)
    at java.lang.Thread.run(Thread.java:745)
```

In the other case, which is probably caused by a bug of mine, I get it when `contains?` is eval-ed on a String.

Maybe we can add a check and execute it only if the response is a map (I could take care of this)?

Has anyone had the same issue with `aleph`?

**Comment by weavejester** [comment]
Ring should throw an error if an invalid response is passed to middleware. I don't see why this is a problem with Ring.

**Comment by arichiardi** [comment]
Mmm so how is it possible that it even get to `ring.session` intact? Something for sure is not right but I will investigate further to check whether it is in ring or aleph

**Comment by arichiardi** [comment]
Ok @weavejester the problem is with `aleph`'s deferred then...a solution has been proposed in the linked issue. Unfortunately though `session-options` is not public. I don't know if you are for making it so...it would be great of course for `aleph`'s users but I understand if you don't want to.

**Comment by weavejester** [comment]
Rather than make `session-options` public, I think it would be a better idea to integrate it into `session-request` and `session-response`. Would that work for you?

**Comment by arichiardi** [comment]
Yes it would work perfectly

**Comment by arichiardi** [comment]
Thanks a lot @weavejester. Also, I need to investigate further but Aleph does not support cookie stores...I don't know what I can do about that at the moment, but it would be great to have a conditional around [this](https://github.com/ring-clojure/ring/blob/master/ring-core/src/ring/middleware/session.clj#L27) so that it prevents an error while trying to apply the protocol to `nil`.
Or maybe at this point is better to use a completely custom session middleware...

**Comment by weavejester** [comment]
Integrating `session-options` into `session-request` is more difficult than I assumed, as I don't want to incur additional performance costs. I'll look into this and see if I can come up with a good solution.

**Comment by weavejester** [comment]
Aleph compatibility should now be made trivial by 1.6.0 betas.
